In [1]:
import torch

In [23]:
#create a random tensor with size (7, 7)

torch.rand(size = (7, 7))

tensor([[0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
        [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056],
        [0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038]])

In [24]:
# matrix multiplication using torch
a = torch.rand(size = (1, 7))
b = torch.rand(size = (1, 7))
torch.matmul(a, b.T)

tensor([[3.0249]])

In [25]:
#create a random tensor with size (7, 7)
#seed set to zero
torch.manual_seed(0)
torch.rand(size = (7, 7))

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [32]:
#seed set to zero
torch.manual_seed(0)
a = torch.rand(size = (2, 3))
b = torch.rand(size = (2, 3))
mul = torch.matmul(a, b.T)
mul

tensor([[0.9722, 0.6174],
        [0.6292, 0.4455]])

In [33]:
mul.max()

tensor(0.9722)

In [38]:
new_tensor = torch.rand(size = (1, 1, 1, 10))
new_tensor

tensor([[[[0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362, 0.1852, 0.3734,
           0.3051, 0.9320]]]])

In [39]:
sq_new_tensor = new_tensor.squeeze()
sq_new_tensor

tensor([0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362, 0.1852, 0.3734, 0.3051,
        0.9320])